### ISSUE TITLE
[Bug]: Layers not working as expected

### ISSUE THREAD

**Issue by cyberhirsch** [zero01101/openOutpaint#268] opened 2023-11-07 11:38 UTC
### Is ths issue about the extension?

- [X] Yup, this is for sure about the extension

### What happened?

When i use image to image it doesn't automatically create a new Layer.
When i merge down the layers also doesn't work as expected. either the Layer above or below will get lost and only one of the two layers remains.

### Steps to reproduce the problem

Since i haven't heard anyone else having that issue, it might be hard to reproduce.
But what i did is
Img2Img 
Merge down.

### What should have happened?

When using Img2Img a new layer should pop up.
When merging down, two layers should be combined.

### Commit where the problem happens

a4a0200f

### What platforms do you use to access openOutpaint?

Windows

### What browsers do you use to access the UI ?

Brave

### Browser Extensions/Addons

Move One Downloader
QR Code Generator

### AUTOMATIC1111 webUI Commandline Arguments

--xformers --api

**Comment by zero01101** [comment] 2023-11-11 14:40
disclaimer: apologies for the extended delay, my brain is terrible and you shouldn't expect much from me)

you've got [new layer per dream](https://github.com/zero01101/openOutpaint/wiki/Manual#gear) enabled i presume?  i can't reproduce the layer merge issue, can you [export a workspace](https://github.com/zero01101/openOutpaint/wiki/Manual#openoutpaint-window) after this occurs and upload it?

**Comment by Reshaflame** [comment] 2023-11-12 05:28
I also have layers problem since the chrome latest update:
when I have 2 layers and I try to merge them together - instead of merging the two layers content, It leaves only the top layer's content and removes the bottom layer's content.
Also - when I work on one layer and have content in it, when I make img2img or dream action upon it and approve the result, the only content that remains is the content just made by the said img2img/dream.
I can play with the History stages to get the content back, but it's annoying.

**Comment by zero01101** [comment] 2023-11-18 18:36
more disclaimer: i warned you my brain is terrible and you shouldn't expect much from me lol

confirming miserable garbage with merging as well as [new dreams deleting previous layer contents without new layer per dream](https://github.com/zero01101/openOutpaint-webUI-extension/issues/66) in chromium-based browsers - likely both the same issue with whatever new canvas "feature" has been recently implemented in chromium...

**Comment by zero01101** [comment] 2023-12-02 19:53
so hey, uh this potentially APPEARS to be an upstream issue with chromium, because with chrome v119.0.6045.200 (Official Build) (64-bit) on win11x64 i'm no longer experiencing this at all?  edge seems to still be affected and i haven't tried brave/opera/other chromium-dependent browsers but given that chrome itself works, i bet the rest will see the issue alleviate with time... 

can anyone else confirm if the issue is gone on most recent chrome?

**Comment by Reshaflame** [comment] 2023-12-09 13:46
It suddenly fixed itself today 😳 I swear that yesterday I still fought with it but today it's fine 😅

**Comment by bkrew** [comment] 2023-12-09 15:09
Im primarily used Brave, now with Chromium Version 120.0.6099.71. the issue seems to be gone. It´s working for me now, but i can give everyone the advice to check the settings. Many Browsers tend to change the settings after an update an reactivate Adblockers and so on. This can cause issues with send pictures to... option. 
@Zero01101 thank you for your work, im working with python and stable diffusion for 6 Months now and still fail at simple tasks. So thumbs up for this tool you share with us.

**Comment by zero01101** [comment] 2023-12-24 14:28
tentatively closing because i THINK this is "fixed" now but by the grace of google and chromium upstream 🤞

**Closed by zero01101** 2023-12-24 14:28 UTC
Labels: bug
