### ISSUE TITLE
[Bug]: Selection tool resize handles not working.

### ISSUE THREAD

**Issue by irldoggo** [zero01101/openOutpaint#277] opened 2023-12-15 14:15 UTC
### What happened?

When using the selection tool, if you have "Keep Aspect Ratio" unchecked you cannot resize the selection, it works if "Keep Aspect Ratio" is checked. The issue is repeatable on any browser, with and without browser extensions, using the standalone or the A1111 integrated version. 

### Steps to reproduce the problem

1. Use Selection Tool.
2. Disable Keep Aspect Ratio.
3. Try to resize the selection.

### What should have happened?

It should resize!

### Commit where the problem happens

latest

### What platforms do you use to access openOutpaint?

Windows, Linux

### What browsers do you use to access the UI ?

Mozilla Firefox, Google Chrome, Brave

### Browser Extensions/Addons

I have run it with and without browser extensions. I even did a fresh install of Chrome to see if that would solve the issue. So extensions are not the issue.

### AUTOMATIC1111 webUI Commandline Arguments

--api --listen --xformers --cors --allow-unsecure

### Additional information

The resize handles work just fine if you have "Keep Aspect Ratio" selected. So I don't think there is a problem with interacting with the handles. This doesn't seem to be a browser or a platform issue.

**Comment by Hangover3832** [comment] 2023-12-15 16:35
Should be fixed with #276. Hope this project is still alive.

**Comment by irldoggo** [comment] 2023-12-15 16:46
Same, probably the best current implementation of outpainting that exists. Invoke is painful, A1111's outpaint script is... well, useless nearly. The other outpainting web project is closed source. Krita's SD plugins constantly break. So yeah, props to the Dev on this.

**Comment by Hangover3832** [comment] 2023-12-15 16:56
I do not even get something useful inpaintinted in Krita SD, even though its a very nice implemented plugin. @irldoggo, can you please verify that this commit fixes the issue for you?

**Comment by irldoggo** [comment] 2023-12-15 17:11
Has your commit been merged? I am not too sure how to pull a PR manually. Unless I just clone your repo? @Hangover3832

**Comment by Hangover3832** [comment] 2023-12-15 17:18
It has not been merged yet. Best is to clone https://github.com/Hangover3832/openOutpaint.git into a new location. GitHub Desktop makes it easy to switch to the branch "mask_blur_fix".

**Comment by irldoggo** [comment] 2023-12-15 17:20
I am a commandline boy. Haha, Ill test it out and report back.

**Comment by irldoggo** [comment] 2023-12-15 17:31
@Hangover3832 So it does seem that my initial problem is fixed with your commit, nice job! Though is the behavior supposed to be that when you resize one handle it mirrors the motion on the opposite side? This happens when mirror selection is enabled or disabled.

**Comment by Hangover3832** [comment] 2023-12-15 17:44
I cannot reproduce the mirroring issue, neither in firefox nor in edge. Unless you resize the selection to the opposite size, in whitch case mirroring of course is expected and desired.

**Comment by irldoggo** [comment] 2023-12-15 17:48
Hmm. I tried it in Brave and in firefox. With mirroring off, If I drag the bottom left handle, and move it in one square for example, the handles on the right also move in a square. If that is how it's supposed to work, all good then. I just expected I could move one side closer to the other without the other moving.

**Comment by Hangover3832** [comment] 2023-12-15 17:53
Ok, now I understand. I guess that is how it's supposed to work this way. You have to move the selection afterwards.

**Comment by irldoggo** [comment] 2023-12-15 17:57
I'll just hope that it can be a bit more intuitive in the future, haha. Thank you for your help. I'll close this issue then.

**Comment by Hangover3832** [comment] 2023-12-15 17:59
> .... I'll close this issue then.

Unless my PR does not get merged.

**Closed** 2023-12-15 17:59 UTC
Labels: bug

**Comment by zero01101** [comment] 2023-12-16 12:34
enormous thanks to @Hangover3832 for the gracious fixes! yeah, this app/repo/project/toy definitely moves a lot slower these days because i'm kind of a disaster and catastrophe lol but definitely not dead yet ;)
