### ISSUE TITLE
[Bug]: After pressing "Y" the canvas is cleared, only the last generation remains

### ISSUE THREAD

**Issue by BenderBlender** [zero01101/openOutpaint#272] opened 2023-12-05 07:11 UTC
### What happened?

After clicking on "Y" (or "ENTER" after generation), the canvas is completely cleared, leaving only the square with the latest generation. So it’s not possible to use the editor normally.

### Steps to reproduce the problem

1. Generate first image
2. Press "Y" (all ok)
3. Generate second image (in the other place of canvas)
4. Press "Y" (all canvas cleared, except for the square with the current generation)

### What should have happened?

After clicking on "Y" (or "ENTER" after generation), the canvas is completely cleared, leaving only the square with the latest generation. So it’s not possible to use the editor normally.

### Commit where the problem happens

-

### What platforms do you use to access openOutpaint?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Browser Extensions/Addons

-

### AUTOMATIC1111 webUI Commandline Arguments

@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=--theme=dark --opt-sdp-no-mem-attention --no-half-vae --opt-channelslast --api
set SAFETENSORS_FAST_GPU=1

call webui.bat

### Additional information

-

**Comment by BenderBlender** [comment] 2023-12-05 07:16
Checked it in browser Microsoft Edge, everything is the same, so it's not because of the browser

**Comment by zero01101** [comment] 2023-12-09 13:33
closing as duplicate of https://github.com/zero01101/openOutpaint/issues/268

**Closed by zero01101** 2023-12-09 13:33 UTC
Labels: bug

**Comment by zero01101** [comment] 2023-12-09 13:53
seems chromium upstream is really seeming to be the culprit here; if anyone still affected could confirm the findings in https://github.com/zero01101/openOutpaint/issues/268#issuecomment-1848414152 that'd be awesome :)

**Comment by BenderBlender** [comment] 2023-12-09 19:41
After the last update everything worked! Thank you very much!
