### ISSUE TITLE
No square zone with cursor on Chrome. 

### ISSUE THREAD

**Issue by DanteStormwind** [zero01101/openOutpaint#92] opened 2022-12-12 01:47 UTC
When i open outpaint on Chrome there is no square frame on cursor, only regular cursor, so i cant see outpaint zone clearly. 

To Reproduce:
Open: http://127.0.0.1:3456/ in Google Chrome v108.0.5359.99

![Снимок 2022-12-12 04 33 47](https://user-images.githubusercontent.com/120347703/206942950-4d7d2237-bc85-4f34-817e-73b92eedd689.png)

On the OperaGX works as intended:
![openOutpaint 🐠 - Opera 2022-12-12 04 44 09](https://user-images.githubusercontent.com/120347703/206943659-f33c2ea8-d2c1-4220-982d-d21320dd221a.png)

- OS: Windows 10
- Browser: Google Chrome
- Version 108.0.5359.99
- WebUI up to date (updates each time i launch it).

**Comment by zero01101** [comment] 2022-12-12 01:59
can't confirm locally with same chrome on win10 x64 19045.2251 :/ 

![image](https://user-images.githubusercontent.com/1649724/206944916-49dc67b5-c985-44f0-a7d4-5077544979b9.png)

![image](https://user-images.githubusercontent.com/1649724/206944928-448d7e4b-6c74-4c4e-be71-91739a3e813a.png)

are there any errors listed in the F12 console?

**Comment by seijihariki** [comment] 2022-12-12 02:39
Do the brush tools work?

**Comment by seijihariki** [comment] 2022-12-12 02:56
It seems the overlay canvas is just broken... If you click with the dream tool does the progress bar and such appear?

**Comment by DanteStormwind** [comment] 2022-12-12 03:03
Yep. Here it is. Generation works too. Tried it out before. I can then accept it and start new gen nearby, just had to find right spot for them to be in line.
![openOutpaint 🐠 - Google Chrome 2022-12-12 06 01 0](https://user-images.githubusercontent.com/120347703/206951586-6b14a205-ad43-40e4-a52b-f4a0e298451f.png)

**Comment by zero01101** [comment] 2022-12-12 03:05
yeah, still no luck on reproducing this locally yet :/

**Comment by seijihariki** [comment] 2022-12-12 04:16
Will create a new branch tomorrow to test some of my suspicions. @DanteStormwind could you checkout this new branch, so we can get to the bottom of this?

I'll post a comment here when I get to it.

**Comment by DanteStormwind** [comment] 2022-12-12 04:26
Shure.

**Comment by seijihariki** [comment] 2022-12-12 13:10
Okay, try checking out the i92 branch version (`git checkout i92`) and take a screenshot of the console. The screen should also be reddish.

**Comment by DanteStormwind** [comment] 2022-12-12 15:48
Done. Nothing changed.
![openOutpaint 🐠 - Google Chrome 2022-12-12 18 39 2](https://user-images.githubusercontent.com/120347703/207088452-b0c5d344-ec88-4e78-ac7b-f08edab9c9d0.png)

**Comment by seijihariki** [comment] 2022-12-12 16:14
Can you go to the network tab, disable caching and try again?

**Comment by DanteStormwind** [comment] 2022-12-12 16:23
Done. Now its red.
![openOutpaint 🐠 - Google Chrome 2022-12-12 19 21 1](https://user-images.githubusercontent.com/120347703/207098223-c95bf9ff-d781-405a-97a1-75c4f55c6de6.png)
![openOutpaint 🐠 - Google Chrome 2022-12-12 19 21 3](https://user-images.githubusercontent.com/120347703/207098250-7c0af82e-7aa8-43d7-9cf7-bd886d18242f.png)

**Comment by seijihariki** [comment] 2022-12-12 16:57
Hm... still no cursor?

**Comment by DanteStormwind** [comment] 2022-12-12 17:03
Nope. Still nothing.

**Comment by seijihariki** [comment] 2022-12-13 01:48
Hm... That should have printed some debugging info in the console.

Is there some way I can contact you more easily so not to pollute the conversation here? You can DM me on Reddit (u/seijihariki) if you find it okay to schedule a call or something to fix this more effectively. It's also completely fine if you prefer to continue debugging here, it will just take longer, probably.

**Comment by DanteStormwind** [comment] 2022-12-13 03:31
Fine. I messaged you.

**Comment by royvandewater** [comment] 2023-01-28 18:40
I'm getting a similar issue in both Chrome & Firefox on HEAD (c7a68f3e37eaea954f0ce0030438e47ec9659848).

Whenever I select the Dream tool, I get a console error. The error is different in Chrome than it is in Firefox:

Chrome:
![image](https://user-images.githubusercontent.com/72016/215285116-22d8fcae-0ec7-447b-acbe-3ed40601f033.png)

FireFox:
![image](https://user-images.githubusercontent.com/72016/215285127-63b5f3c0-1b0d-407c-8063-85ab314b3919.png)

**Comment by royvandewater** [comment] 2023-01-28 18:47
I checked out an older version (bd5581fdbf3a7dbe1637ece4684a0fb18129aacd) and everything worked as expected in Chrome. When I went back to HEAD, it continued to work in Chrome. I never refreshed the page while looking at the old version in FireFox and it still doesn't work.

**Comment by zero01101** [comment] 2023-01-28 18:52
i'm unable to reproduce that error on firefox or chrome (v109 both) on win10x64; could you try refreshing firefox without cache? i know the js hashes should take care of that but hey

**Comment by royvandewater** [comment] 2023-01-28 19:01
I tried clearing the cache and refreshing, also tried opening a private window in FireFox and it doesn't work. My hypothesis is that HEAD can't bootstrap into a valid state but that the older version can. If true, I should be able to checkout the old version, refresh FireFox, see it work, then checkout HEAD and it should continue to work.

...

Confirmed, that fixes it in my FireFox Private window while still being broken in my regular window (which I did not refresh while I had the old version checked out)

**Comment by zero01101** [comment] 2023-01-28 19:08
>My hypothesis is that HEAD can't bootstrap into a valid state but that the older version can. 
>(which I did not refresh while I had the old version checked out)

i mean i admit regularly to being an idiot so i could very easily be missing the point, but i guarantee openOutpaint doesn't magically update its JS to the newest version in the background if you `git pull` while it's up and running without refreshing the page ;) i still can't recreate the issue you mentioned however...

**Comment by royvandewater** [comment] 2023-01-28 19:13
Sorry, I think I didn't describe what I thought was happening. I think that the JS code in the older version was able to get FF into a coherent state and that the HEAD of main cannot. I believe this state is something that's stored in local, session, or cookie store. I can reliably get either browser back into that incoherent state by opening the latest version in an incognito window.

**Comment by zero01101** [comment] 2023-01-28 19:16
ahh ok yeah this seems very uhhh different and bad lol, yeah first run in incognito mode is exposing some oversights

**Comment by zero01101** [comment] 2023-01-28 20:37
alright so https://github.com/zero01101/openOutpaint/commit/abde86d6b64af94eabaf3412124ed1dc90ce0213 should at least let new installs work - @royvandewater care to check?  it's not an elegant fix but should at least prevent the error i believe

**Comment by royvandewater** [comment] 2023-01-30 16:04
The latest version works for me in Incognito, thanks for the quick fix!

**Comment by zero01101** [comment] 2023-01-30 22:58
will be closing this then as the original post is well over a month out now

**Closed by zero01101** 2023-01-30 22:58 UTC
Labels: bug
