### ISSUE TITLE
[Bug]: No angle correction for flip option on stamp

### ISSUE THREAD

**Issue by seijihariki** [zero01101/openOutpaint#203] opened 2023-02-26 15:04 UTC
### What happened?

Angles are not corrected with flip enabled on stamp. Also, flip may be kind of redundant, as we already have rotation + mirror, which have the same capabilities, and flip + mirror is equivalent to 180º rotation, and flip is equivalent to 180º rotation + mirror...

### Steps to reproduce the problem

1. Enable flip
2. Try rotating the stamp after that

### What should have happened?

Angle correction to be applied after flip for compositing transformations.

### Commit where the problem happens

a71b52464ddb4d67f4771c32c47f81459c06d9f4

### What platforms do you use to access openOutpaint?

Linux

### What browsers do you use to access the UI ?

Mozilla Firefox

### Browser Extensions/Addons

N/A

### AUTOMATIC1111 webUI Commandline Arguments

N/A

### Additional information

https://user-images.githubusercontent.com/7552751/221419000-1a7fe9f0-2a05-4500-84f0-a9f36a93bfd6.mp4

**Comment by zero01101** [comment] 2023-02-26 15:36
lmao whoops  
![lil bad pokerface](https://user-images.githubusercontent.com/1649724/221420320-7c4b72ee-a370-4724-9794-c6a24db45f61.png)  
should be fixed now on https://github.com/zero01101/openOutpaint/commit/e1a694281ee0d7fe410e913166644884ec048b82 with my apologies and thanks for noticing :D 

>Also, flip may be kind of redundant, as we already have rotation + mirror, which have the same capabilities, and flip + mirror is equivalent to 180º rotation, and flip is equivalent to 180º rotation + mirror...

🤦 have i ever mentioned how i failed math three times in a row

yes confirmed this is redundant and unnecessary but due to dumdums like me, i bet if it wasn't there someone (i.e. me) would've been HEY WHY NO VERTICAL FLIP TOO

**Closed by zero01101** 2023-02-26 15:36 UTC
Labels: bug
