### ISSUE TITLE
[Bug]: 500 internal server error with latest webui

### ISSUE THREAD

**Issue by JustNeutral0** [zero01101/openOutpaint#212] opened 2023-03-15 08:36 UTC
### What happened?

ran openOutpaint with newest version of webui, all tools report 500 internal server errors

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ... [etc]

### What should have happened?

ran properly

### Commit where the problem happens

latest

### What platforms do you use to access openOutpaint?

Windows

### What browsers do you use to access the UI ?

Google Chrome, Other (please list in additional information)

### Browser Extensions/Addons

adblock and better ttv (twitch addon)

### AUTOMATIC1111 webUI Commandline Arguments

--theme dark --xformers --medvram --listen --enable-insecure-extension-access --always-batch-cond-uncond --api --cors-allow-origins=http://localhost:3456

### Additional information

using opera gx browser, same issue happens with chrome

**Comment by zero01101** [comment] 2023-03-15 23:38
so i'm actually kind of wondering if you're running into something like [the issue i just opened upstream](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8666)

**Comment by JustNeutral0** [comment] 2023-03-15 23:55
It was actually something about a reference being undefined in the dream script, ill try and get an error code when i get home

> so i'm actually kind of wondering if you're running into something like [the issue i just opened upstream](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8666)

**Comment by JustNeutral0** [comment] 2023-03-15 23:56
Sorry about that

**Comment by zero01101** [comment] 2023-03-15 23:57
lmao no worries at all, your report got me to check on what might be happening and ran into something undesirable in the meantime, so, uh thanks? :D

**Comment by JustNeutral0** [comment] 2023-03-16 00:18
![Screenshot_20230315-191414_F12](https://user-images.githubusercontent.com/116992951/225476530-ffac08a7-78b2-4699-a605-71e0f0fb012a.jpg)
Thats all i got with mobile, what im using to bring up the console wont let me get more details

**Comment by JustNeutral0** [comment] 2023-03-16 00:30
Does it with any of the tools just about

**Comment by JustNeutral0** [comment] 2023-03-16 07:19
![image](https://user-images.githubusercontent.com/116992951/225542904-fc59a05f-cbdd-480a-b8d1-8b47343d4b2a.png)
some more details

**Comment by zero01101** [comment] 2023-03-16 23:22
i'm still pretty sure it's going to be happening in webUI as there's really nothing in openOutpaint that could even return a 500 unless you're running it standalone and something's really wrong with python's webserver... 

- what's the content in the webUI console when that occurs?
- if you follow the reproduce steps in that issue i linked does it happen just over standard API calls? 
```
    Go to [local API docs](http://127.0.0.1:7860/docs)
    Scroll down to POST sdapi/v1/txt2img, open it, click "try it out"
    Paste the following into the input field

{
	"batch_size": 1,
	"cfg_scale": 7,
	"enable_hr": false,
	"height": 512,
	"n_iter": 1,
	"negative_prompt": "test",
	"prompt": "test",
	"restore_faces": false,
	"sampler_index": "DDIM",
	"seed": "1",
	"steps": 1,
	"width": 512
}
```
 - could you possibly supply the content of the POST request parameters and response from your browser's network tab?
 
![image](https://user-images.githubusercontent.com/1649724/225773631-a1706683-e815-44d3-982c-6c296e0bdae4.png)
![image](https://user-images.githubusercontent.com/1649724/225773720-5d61a1a3-ae70-480b-8d8c-cf72db67c603.png)

**Comment by JustNeutral0** [comment] 2023-03-16 23:27
Will do when i get home later

**Comment by JustNeutral0** [comment] 2023-03-17 18:46
![image](https://user-images.githubusercontent.com/116992951/225991979-1a0dc102-5b9c-4530-a791-2e47edc24721.png)
![image](https://user-images.githubusercontent.com/116992951/225992053-4369c76f-f9a1-41ad-997d-571288c018d8.png)
is that what you needed?

**Comment by zero01101** [comment] 2023-03-18 00:43
almost - was hoping for the content of the payload tab in the first image but that should'nt be any different than what was passed through the API input field... unfortunately your results seem to confirm what i was thinking - looks like you've got something that's causing an issue with webUI and its API deeper than openOutpaint :( 

not sure what A1111 extensions (etc) you've got going (and i might need to ask that in the issue template) but the _easiest_ way to test that everything's working as expected from the very bottom would be to simply install a second "clean" copy of webUI to a different directory, enable the `--api` flag on that and ensure that the txt2img API request returns a base64 image string and a status of 200

**Comment by zero01101** [comment] 2023-03-18 00:45
will be closing this as it's occurring in webUI; please reopen if the issue can be reproduced after confirming base webUI API functionality :)

**Closed by zero01101** 2023-03-18 00:45 UTC
Labels: external

**Comment by zero01101** [comment] 2023-03-18 00:50
...just out of curiosity, does it happen if you use http://127.0.0.1:7860 instead of http://localhost:7860 ?

**Comment by JustNeutral0** [comment] 2023-03-18 01:54
I use --listen, but i haven't tried it with 127.0.0.1:7860, will attempt when i get home
