### ISSUE TITLE
[Bug]: Latest Automatic WebUI breaks openOutpaint

### ISSUE THREAD

**Issue by vladmandic** [zero01101/openOutpaint#183] opened 2023-01-23 21:58 UTC
### What happened?

Immediately after opening WebUI, it logs errors if `openOutpaint` extension is enabled:

```log
Launching Web UI with arguments: --api --xformers --disable-console-progressbars
WARNING:root:Pytorch pre-release version 2.0.0.dev20230118+cu118 - assuming intent to test it
WARNING:root:Pytorch pre-release version 2.0.0.dev20230118+cu118 - assuming intent to test it
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights [cc6cb27103] from /home/vlado/dev/automatic/models/Stable-diffusion/sd-v15-runwayml.ckpt
Loading VAE weights specified in settings: /home/vlado/dev/automatic/models/VAE/vae-ft-mse-840000-ema-pruned.ckpt
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(1): buffy
Model loaded in 8.0s (0.2s create model, 7.2s load weights).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/vlado/.local/lib/python3.10/site-packages/anyio/streams/memory.py", line 94, in receive
    return self.receive_nowait()
  File "/home/vlado/.local/lib/python3.10/site-packages/anyio/streams/memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock
...
  File "/home/vlado/dev/automatic/modules/api/api.py", line 255, in extras_single_image_api
    reqDict['image'] = decode_base64_to_image(reqDict['image'])
  File "/home/vlado/dev/automatic/modules/api/api.py", line 56, in decode_base64_to_image
    return Image.open(BytesIO(base64.b64decode(encoding)))
  File "/home/vlado/.local/lib/python3.10/site-packages/PIL/Image.py", line 3283, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f5de5d06200>
```

Issue is that `openOutpaint` makes an invalid request to `/sdapi/v1/extra-single-image`

And yes, inside openOutpaint that request is even marked as ignorable/invalid

```js
                const response = await fetch(extras_url, {
			method: "POST",
			headers: {
				Accept: "application/json",
				"Content-Type": "application/json",
			},
			body: JSON.stringify(purposefully_incorrect_data),
		});
		const data = await response.json();

		console.log(
			"[index] purposefully_incorrect_data response, ignore above error"
		);
```

But the issue is that it now actually breaks WebUI ?!

There has to be a better way than to post invalid request and try to ignore it?

Why not use `/sdapi/v1/upscalers` endpoint?

And yes, invalid request should not break WebUI - I'll do a PR to do graceful handling of invalid API requests on WebUI server side.

But it still needs to be address in the extension itself.

### Steps to reproduce the problem

N/A

### What should have happened?

N/A

### Commit where the problem happens

fc8e6fb557832320a770af80ec661d59f99878a4

### What platforms do you use to access openOutpaint?

Windows

### What browsers do you use to access the UI ?

Microsoft Edge

### Browser Extensions/Addons

N/A

### AUTOMATIC1111 webUI Commandline Arguments

N/A

**Comment by seijihariki** [comment] 2023-01-23 22:07
The issue was mostly that we didn't have any way to reliably fetch valid upscaler names. The upscaler getting endpoint returned inconsistently, some using the name, others using model_name for valid upscaler parameter value, and it was impossible to determine automatically which used what values for a parameter.

Will see what we can do... still, a 500 error on the API should not crash the webui... I am having the same issue, it returns a 500 but the only thing that happens is that my upscalers list is empty:

![image](https://user-images.githubusercontent.com/7552751/214160668-0a275fe1-e650-4748-8761-b8a76758fa18.png)

**Comment by vladmandic** [comment] 2023-01-23 22:15
The problem that on server side, it was not a 500 error, it blindly tried to decode a null image and PIL crashed.
I've just added exception handling in PR <https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/7140>, now it will be actual 500 error

Now, if you have issues using `/sdapi/v1/upscalers` endpoint, let me know and i can take a look at it....

**Comment by seijihariki** [comment] 2023-01-23 22:26
Can you give it a look now? Upscalers still not working, but at least should always send a valid image. (Now sure why it would not send a valid image before, but well...)

**Comment by vladmandic** [comment] 2023-01-23 22:28
sorry, i cant now, just stepped out for dinner (typing on cellphone while waiting for uber)

**Comment by zero01101** [comment] 2023-01-23 23:16
sigh
as mentioned, the "official" endpoints are unreliable and have returned [trash data](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/6899) since we _introduced_ upscaler support on this app, literally months ago, and even now it doesn't provide complete output - for example, i've got remacri installed but it doesn't show up anywhere in upscalers or realesrgan API endpoints, plus it lists realesrgan models i don't have installed (which is likely by design)

![image](https://user-images.githubusercontent.com/1649724/214173243-06074bc5-99a0-4281-92f6-45fa4dcb5393.png)

```
curl -X 'GET' \
  'http://127.0.0.1:7860/sdapi/v1/upscalers' \
  -H 'accept: application/json'
  
  [
  {
    "name": "None",
    "model_name": null,
    "model_path": "E:\\storage\\stable-diffusion-webui\\models\\None",
    "model_url": null
  },
  {
    "name": "Lanczos",
    "model_name": null,
    "model_path": null,
    "model_url": null
  },
  {
    "name": "Nearest",
    "model_name": null,
    "model_path": null,
    "model_url": null
  },
  {
    "name": "ESRGAN",
    "model_name": "ESRGAN_4x",
    "model_path": "E:\\storage\\stable-diffusion-webui\\models\\ESRGAN",
    "model_url": "https://github.com/cszn/KAIR/releases/download/v1.0/ESRGAN.pth"
  },
  {
    "name": "ESRGAN",
    "model_name": "ESRGAN_4x",
    "model_path": "E:\\storage\\stable-diffusion-webui\\models\\ESRGAN",
    "model_url": "https://github.com/cszn/KAIR/releases/download/v1.0/ESRGAN.pth"
  },
  {
    "name": "RealESRGAN",
    "model_name": null,
    "model_path": "E:\\storage\\stable-diffusion-webui\\models\\RealESRGAN",
    "model_url": null
  },
  {
    "name": "RealESRGAN",
    "model_name": null,
    "model_path": "E:\\storage\\stable-diffusion-webui\\models\\RealESRGAN",
    "model_url": null
  },
  {
    "name": "RealESRGAN",
    "model_name": null,
    "model_path": "E:\\storage\\stable-diffusion-webui\\models\\RealESRGAN",
    "model_url": null
  },
  {
    "name": "RealESRGAN",
    "model_name": null,
    "model_path": "E:\\storage\\stable-diffusion-webui\\models\\RealESRGAN",
    "model_url": null
  },
  {
    "name": "LDSR",
    "model_name": null,
    "model_path": "E:\\storage\\stable-diffusion-webui\\models\\LDSR",
    "model_url": "https://heibox.uni-heidelberg.de/f/578df07c8fc04ffbadf3/?dl=1"
  },
  {
    "name": "SwinIR",
    "model_name": "SwinIR 4x",
    "model_path": "E:\\storage\\stable-diffusion-webui\\models\\SwinIR",
    "model_url": "https://github.com/JingyunLiang/SwinIR/releases/download/v0.0/003_realSR_BSRGAN_DFOWMFC_s64w8_SwinIR-L_x4_GAN.pth "
  }
]
```

```
curl -X 'GET' \
  'http://127.0.0.1:7860/sdapi/v1/realesrgan-models' \
  -H 'accept: application/json'
  
  [
  {
    "name": "R-ESRGAN General 4xV3",
    "path": "https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.5.0/realesr-general-x4v3.pth",
    "scale": 4
  },
  {
    "name": "R-ESRGAN General WDN 4xV3",
    "path": "https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.5.0/realesr-general-wdn-x4v3.pth",
    "scale": 4
  },
  {
    "name": "R-ESRGAN AnimeVideo",
    "path": "https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.5.0/realesr-animevideov3.pth",
    "scale": 4
  },
  {
    "name": "R-ESRGAN 4x+",
    "path": "https://github.com/xinntao/Real-ESRGAN/releases/download/v0.1.0/RealESRGAN_x4plus.pth",
    "scale": 4
  },
  {
    "name": "R-ESRGAN 4x+ Anime6B",
    "path": "https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.2.4/RealESRGAN_x4plus_anime_6B.pth",
    "scale": 4
  },
  {
    "name": "R-ESRGAN 2x+",
    "path": "https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.1/RealESRGAN_x2plus.pth",
    "scale": 2
  }
]
```

previously submitting a null image and invalid sampler to `/sdapi/v1/extra-single-image` would return a perfectly usable list of

**Comment by AUTOMATIC1111** [comment] 2023-01-24 07:09
`/sdapi/v1/upscalers` should be working properly in latest version :^)

**Comment by relocator** [comment] 2023-01-24 21:18
I'm also getting a crash at startup on a fresh install. I updated to newest Automatic a few mins ago, and the openoutpaint tab is gone, and I'm getting errors in startup. Seems like an issue with adding the tab to the webUI?
![callback error](https://user-images.githubusercontent.com/51518899/214418444-d80e2ec8-3aa8-4980-856a-f929e0eeaabd.jpg)

**Comment by seijihariki** [comment] 2023-01-24 22:45
Seems some problem with setting up the arguments for openOutpaint. Added error handling to avoid fully breaking even if arguments were not set up properly.

**Comment by zero01101** [comment] 2023-01-24 22:58
>/sdapi/v1/upscalers should be working properly in latest version :^)

the man himself!  confirmed and muchly obliged :D  fixed in https://github.com/zero01101/openOutpaint/commit/bd5581fdbf3a7dbe1637ece4684a0fb18129aacd 

>Seems like an issue with adding the tab to the webUI?

yeah, closing and re-starting webUI would've fixed that by instantiating the preload.py, but 

>Added error handling to avoid fully breaking even if arguments were not set up properly.

lol always a few minutes faster than me ;) was just about to push a nearly identical commit myself

**Closed by zero01101** 2023-01-24 22:58 UTC
Labels: bug
