### ISSUE TITLE
[Bug] Saving fails silently if canvas is too big

### ISSUE THREAD

**Issue by TiagoTiago** [zero01101/openOutpaint#93] opened 2022-12-12 07:15 UTC
**Describe the bug**
Nothing happens when I click save if the canvas or the selection is too big (I forgot the exact number, but something around 3712 or a little under it was the maximum that got saved).

**To Reproduce**
Set canvas to 4096x4096, refresh the page to get the new size applied, generated all over, try to save. Also, select a region of similarly high size and try saving it.

**Expected behavior**
Any size should save, or at least provide a clear error message explaining what's going on if it fails.

**Desktop (please complete the following information):**

- OS: Linux
- Browser: Firefox
- Version: f279c84 commit from the testing branch (not sure if this is how I should specify it, I pulled right after seeing the message about it on issue #89 to test, as suggested there)

**Comment by seijihariki** [comment] 2022-12-12 11:15
Yeah, that's an issue... We do have a problem in which newly added resources are not saved between sessions due to localStorage quotas, but I guess that is a separate problem

**Comment by seijihariki** [comment] 2022-12-13 02:12
@zero01101 can you replicate this issue?

**Comment by zero01101** [comment] 2022-12-13 03:11
unfortunately i cannot :/ 

![image](https://user-images.githubusercontent.com/1649724/207217152-305cca16-eb67-4193-822c-882f88da1f71.png)

**Comment by TiagoTiago** [comment] 2022-12-13 04:45
I can no longer reproduce the issue on my end either, not sure what changed; I'll let you know if it shows up again.

**Comment by TiagoTiago** [comment] 2022-12-13 04:57
Correction, got it. Try filling the whole canvas; perhaps that's a requirement to trigger the bug; I could still save while there was plenty of transparent areas, generated a bit, selected an area with the selection tool and stretched it to cover everything, and now it's once again not saving.

Still gotta double-check if that's all or if having also loaded Steam and a bunch of other tabs on Firefox is also involved.

**Comment by TiagoTiago** [comment] 2022-12-13 05:16
Closed Steam and restarted Firefox and both the A1111 and openOutpaint scripts, and still the same. And nothing shows on the console.

**Comment by seijihariki** [comment] 2022-12-13 18:54
Maybe it is a string size thing @zero01101? But I don't think any image could go over the 2 GB Firefox string size limit.

@TiagoTiago can you provide us with the version of Firefox you are using? Could you send a screenshot of the Firefox about information?

This is mine:
![image](https://user-images.githubusercontent.com/7552751/207420081-54867d3d-f729-44d1-9c6e-9c5babee5ff1.png)

If you use a 32-bit version of Firefox, it may affect something, maybe?

**Comment by TiagoTiago** [comment] 2022-12-13 20:41
![Untitled](https://user-images.githubusercontent.com/194285/207438399-3afb9e1d-a340-4a94-b1ae-9ce97d34a8b5.png)

I think the note about updates is probably because Mint has it's own updater app that takes care of everything, and looks like by default it has a slightly customized version of Firefox perhaps? It does seem it's a little behind your version though, but there's no updates available right now thru `apt`. Do you got like a preview version or something, or are they just lagging behind on Mint?

**Comment by seijihariki** [comment] 2022-12-13 20:45
Previous tests were done on 107.0.1, actually... It was just today that firefox updated for me. But yeah, kinda lost on this. Could you try replicating this issue in chromium so we can pinpoint the issue to your browser?

**Comment by seijihariki** [comment] 2022-12-13 20:49
Later today I will create a new branch with some download tests so we can try to find out what is going on.

**Comment by TiagoTiago** [comment] 2022-12-13 21:17
Works on Chromium; and it doesn't seem to be related to addons on Firefox, since it still failed silently when I tried with a new profile.

**Comment by zero01101** [comment] 2022-12-13 23:39
yep, can confirm; i got firefox to download a fully, uh, saturated? image of 4k x 4k, decided to try 8k by 8k, no luck - the save canvas button stays depressed for a bit but no file is downloaded.  trying to stamp that much image data is _really_ annoying let me tell you lol.  GPU memory usage goes nuts and the task manager 3d usage skyrockets too if the tab is active.

profiler during canvas save attempt: 

![image](https://user-images.githubusercontent.com/1649724/207468604-82eaeacf-4343-4b0f-8295-423855fb7676.png)

![image](https://user-images.githubusercontent.com/1649724/207468640-59552a15-1dc0-4512-88c1-77f261fa201a.png)

![image](https://user-images.githubusercontent.com/1649724/207468691-732bfcb0-20a1-481b-9e5b-96fd4505a453.png)

**Comment by seijihariki** [comment] 2022-12-14 01:18
Great! So we were able to reproduce it! Can you pinpoint the problem, @zero01101?

**Comment by seijihariki** [comment] 2022-12-14 01:24
From what I see in the profiler log, it seems to be mostly toDataURL. If we use blobs instead we could probably fix this.

**Comment by zero01101** [comment] 2022-12-14 01:35
>Can you pinpoint the problem, @zero01101?

lmao i think this is the first time in my entire life i've ever used the profiler, but yeah, it looks like it's primarily the base64 conversion running OOM if the GC is complaining this much about over-malloc :/ 

![image](https://user-images.githubusercontent.com/1649724/207483286-ca57c87d-4d05-4e53-954f-473018a5a39b.png)

**Comment by seijihariki** [comment] 2022-12-14 02:57
Can you guys test this last commit? It migrates downloads to use blob objects instead of a dataURL. This should support much bigger images.

**Comment by zero01101** [comment] 2022-12-14 03:32
8k x 8k file downloaded successfully, can't say i'll be holding on to this file long however lol

![image](https://user-images.githubusercontent.com/1649724/207498628-60259ef9-631e-40d7-a660-fccf3492d62e.png)

https://share.firefox.dev/3FPYrjc

**Comment by seijihariki** [comment] 2022-12-16 01:41
As @zero01101 who was able to replicate this issue seems to have the issue resolved, will consider this issue as resolved. We can reopen it if @TiagoTiago continues to have it. Changes will be merged soon into `main`.

**Closed by seijihariki** 2022-12-16 01:41 UTC
Labels: bug, eval
