### ISSUE TITLE
[Bug]: Prompt working but when accepting picture, it only keeps the area it was looking for and cut the rest of the image outside the box.

### ISSUE THREAD

**Issue by Ralph224** [zero01101/openOutpaint#270] opened 2023-11-06 01:03 UTC
### Is ths issue about the extension?

- [X] Yup, this is for sure about the extension

### What happened?

Everything used to work since this weekend.  No update on my end on the webui/installation.  

I select an image that I import from PNG Info and then SEND TO OPENOUTPAINT.
From there, I would select an area where I want to extend the image.  Usually a 512x512 area with some of the area being of the existing image.  Set my prompt and search...  

When I have the results, I used to APPROVE one of them and carry on.  However, the issue I have now is that when I approve, only the 512x512 stays in the Openoutpaint canvas.  The rest of the picture disappear.

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ... [etc]

### What should have happened?

When I approve, the 512x512 image should stay there AND the rest of the image in Openoutpaint that I want to extend.

### Commit where the problem happens

NA

### What platforms do you use to access openOutpaint?

Windows

### What browsers do you use to access the UI ?

Mozilla Firefox

### Browser Extensions/Addons

Firefox

### AUTOMATIC1111 webUI Commandline Arguments

@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS= --deepdanbooru --xformers --api 
set "REQS_FILE=.\extensions\sd_dreambooth_extension\requirements.txt"
set "DREAMBOOTH_SKIP_INSTALL=True"

call webui.bat

### Additional information

 NA

**Comment by zero01101** [comment] 2023-11-18 18:45
moved to main openOutpaint repo even though original issue _was_ indeed extension-specific via send-to button, this is obviously a chromium vs base openOutpaint grumbling

**Comment by zero01101** [comment] 2023-12-02 19:52
probably should've closed as duplicate of https://github.com/zero01101/openOutpaint/issues/268 a while ago... continuing there

**Comment by zero01101** [comment] 2023-12-02 19:57
closing for real this time

**Closed by zero01101** 2023-12-02 19:57 UTC
Labels: bug

**Comment by zero01101** [comment] 2023-12-09 13:52
seems chromium upstream is really seeming to be the culprit here; if anyone still affected could confirm the findings in https://github.com/zero01101/openOutpaint/issues/268#issuecomment-1848414152 that'd be awesome :)
